version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '13:00' # UTC. Equivalent to 22:00 JST
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'npm'
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'daily'
      time: '13:00' # UTC. Equivalent to 22:00 JST
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'npm'
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'daily'
      time: '13:00' # UTC. Equivalent to 22:00 JST
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'npm'
  - package-ecosystem: 'npm'
    directory: '/functions'
    schedule:
      interval: 'daily'
      time: '13:00' # UTC. Equivalent to 22:00 JST
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'npm'
