# .github/labels.yml
labels:
  - name: bug
    description: Something isn't working
    color: d73a4a
  - name: enhancement
    description: New feature or request
    color: a2eeef
  - name: documentation
    description: Improvements or additions to documentation
    color: 0075ca
  - name: question
    description: Further information is requested
    color: d876e3

  # Priority
  - name: P0-critical
    description: Must be fixed ASAP
    color: b60205
  - name: P1-high
    description: High priority but not show-stopper
    color: e99695
  - name: P2-medium
    description: Normal priority
    color: 0e8a16
  - name: P3-low
    description: Low priority / nice-to-have
    color: d4c5f9

  # Status
  - name: triage-needed
    description: Needs initial review and labeling
    color: 006b75
  - name: in-progress
    description: Work has started
    color: 0052cc
  - name: ready-for-review
    description: Waiting for PR review
    color: f9d0c4

  # Area
  - name: frontend
    description: UI / frontend code
    color: 5319e7
  - name: backend
    description: Server / API code
    color: 0366d6
  - name: infra
    description: Infrastructure / CI / deployment
    color: 006b75

  # Size
  - name: size/XS
    description: < 1 hour
    color: 1d76db
  - name: size/S
    description: half day
    color: 0052cc
  - name: size/M
    description: 1 day
    color: 0e8a16
  - name: size/L
    description: 2+ days
    color: 5319e7

  # Lifecycle
  - name: wontfix
    description: Issue will not be worked on
    color: e4e669
  - name: duplicate
    description: Duplicate of another issue
    color: cfd3d7
  - name: invalid
    description: Not a valid bug or feature request
    color: e6e6e6
