console.log(`
Since the E2E tests are passing and the tests didn't actually fail in the previous attempts, there's no severe flaky bug with it.
However, displaying two IDENTICAL 'data-testid="calendar-read-only-banner"' elements with almost the same semantic content is visually confusing and redundant.
In \`CalendarView.test.ts\`, the test probably finds it because \`getByTestId(...).toBeTruthy()\` or \`toHaveCount(0)\` applies globally.
Actually, wait! \`CalendarView.svelte\` has:
\`\`\`
{#if !editability.editable}
    <p class="hint" data-testid="calendar-read-only-banner">Grid views below render this query's result, but nothing can be dragged until it is writable.</p>
{/if}
\`\`\`
and \`CalendarRoleEditor.svelte\` has:
\`\`\`
{#if readOnly}
    <p class="read-only-banner" data-testid="calendar-read-only-banner">{readOnlyReason}</p>
{/if}
\`\`\`
If we remove the one in \`CalendarView.svelte\`, we eliminate the duplicate `data-testid` and the redundant UI element! Wait, `readOnlyReason` is what tells the user *why* it's read only (missing source_kind and source_id). `CalendarView` tells the user that things can't be dragged.
But actually, the `readOnlyReason` generated by `analyzeCalendarEditability` ALREADY includes this information!
Look at `calendarEditability.ts`:
\`\`\`
readOnlyReason: \`Read-only calendar: the query must SELECT both "\${SOURCE_KIND_COLUMN}" and \`
    + \`"\${SOURCE_ID_COLUMN}" so an entry can be addressed for a write. Nothing on this calendar \`
    + "can be dragged until it does.",
\`\`\`
Notice how `readOnlyReason` ends with "Nothing on this calendar can be dragged until it does."
And the `CalendarView` banner says: "Grid views below render this query's result, but nothing can be dragged until it is writable."
They are completely redundant! The `CalendarView` banner is obsolete since `readOnlyReason` is already displayed by `CalendarRoleEditor` when `showSettings` is true.
But wait! If `showSettings` is FALSE, then `CalendarRoleEditor` is NOT rendered!
If `CalendarRoleEditor` is not rendered, the user won't see the reason why they can't drag anything!
So if we just delete it from `CalendarRoleEditor`, they won't see the exact reason (source_kind/source_id missing).
If we delete it from `CalendarView`, they won't see it when `showSettings` is false!

Is there a better way?
Move `readOnlyReason` up to `CalendarView.svelte`, and remove it from `CalendarRoleEditor.svelte`?
Let's check `CalendarRoleEditor.svelte`:
\`\`\`
    {#if readOnly}
        <p class="read-only-banner" data-testid="calendar-read-only-banner">{readOnlyReason}</p>
    {/if}
\`\`\`
If we remove this block from `CalendarRoleEditor` and change `CalendarView` to:
\`\`\`
    {#if !editability.editable}
        <p class="hint" data-testid="calendar-read-only-banner">
            {editability.readOnlyReason}
        </p>
    {/if}
\`\`\`
Then there will only be ONE banner, ALWAYS visible when read-only (whether settings are open or not), and it will provide the specific reason!
`)
