import { expect } from "chai";
import {
    buildDemoScheduleRules,
    DEMO_DAILY_RULE_ID,
    DEMO_ROUTINE_OCCURRENCES_TABLE_ID,
    DEMO_ROUTINE_TEMPLATES_TABLE_ID,
    DEMO_WEEKLY_RULE_ID,
    demoTables,
} from "../../src/demo-content.js";
import { JobExecutor } from "../../src/scheduler/executor.js";
import { castValueForColumn, parseSchemaString } from "../../src/scheduler/Scheduler.js";

// The demo's recurring-task rules are executed here through the real job
// executor (PGlite in a worker thread), exactly as the scheduler runs them:
// same schema, same seeded records, same occurrence setting.
describe("Demo routine schedule rule SQL", function() {
    this.timeout(60000);

    const occurrences = demoTables.find((t) => t.tableId === DEMO_ROUTINE_OCCURRENCES_TABLE_ID)!;
    const templates = demoTables.find((t) => t.tableId === DEMO_ROUTINE_TEMPLATES_TABLE_ID)!;
    const rules = buildDemoScheduleRules();
    const dailyRule = rules.find((r) => r.ruleId === DEMO_DAILY_RULE_ID)!;
    const weeklyRule = rules.find((r) => r.ruleId === DEMO_WEEKLY_RULE_ID)!;

    // The records as the scheduler reads them from Data Storage (plain objects).
    const seededRecords = occurrences.records.map((record) => ({ id: record.id, ...record.values }));
    const templateRecords = templates.records.map((record) => ({ id: record.id, ...record.values }));

    let executor: JobExecutor;

    beforeEach(() => {
        executor = new JobExecutor();
        executor.startWorker();
    });

    afterEach(async () => {
        await executor.stopWorker();
    });

    // The rule reads the templates table and writes into the occurrences one,
    // so the job materializes both relations (target table first), exactly as
    // the scheduler assembles them from the project's table registry.
    const runRule = (ruleId: string, sql: string, occurrenceUtcIso: string, records = seededRecords) =>
        executor.executeJob({
            ruleId,
            schemaSql: occurrences.schemaSql,
            ruleSql: sql,
            records,
            tables: [
                { schemaSql: occurrences.schemaSql, records },
                { schemaSql: templates.schemaSql, records: templateRecords },
            ],
            timezone: "UTC",
            occurrenceUtcIso,
        });

    it("inserts one dated occurrence per daily task definition", async () => {
        const result = await runRule(DEMO_DAILY_RULE_ID, dailyRule.sql, "2026-03-05T00:00:00Z");

        expect(result.success, result.error).to.equal(true);
        expect(result.rows.map((r: any) => r.id).sort()).to.deep.equal([
            "daily-inbox-2026-03-05",
            "daily-standup-2026-03-05",
        ]);
        for (const row of result.rows) {
            expect(row.cadence).to.equal("daily");
            expect(row.occurrence_date).to.equal("2026-03-05");
            expect(row.done).to.equal(false);
        }
    });

    it("inserts one dated occurrence per weekly task definition", async () => {
        const result = await runRule(DEMO_WEEKLY_RULE_ID, weeklyRule.sql, "2026-03-02T00:00:00Z");

        expect(result.success, result.error).to.equal(true);
        expect(result.rows.map((r: any) => r.id).sort()).to.deep.equal([
            "weekly-report-2026-03-02",
            "weekly-review-2026-03-02",
        ]);
        for (const row of result.rows) {
            expect(row.cadence).to.equal("weekly");
            expect(row.occurrence_date).to.equal("2026-03-02");
        }
    });

    it("uses the scheduled occurrence, not the execution time", async () => {
        const result = await runRule(DEMO_DAILY_RULE_ID, dailyRule.sql, "2020-01-02T00:00:00Z");

        expect(result.success, result.error).to.equal(true);
        expect(result.rows.every((r: any) => r.occurrence_date === "2020-01-02")).to.equal(true);
    });

    it("is idempotent: re-running an occurrence does not touch the existing row", async () => {
        const occurrence = "2026-03-05T00:00:00Z";
        const first = await runRule(DEMO_DAILY_RULE_ID, dailyRule.sql, occurrence);
        expect(first.success, first.error).to.equal(true);

        // The row generated by the first run is now part of the table, and the
        // user has ticked its checkbox.
        const withCompleted = [
            ...seededRecords,
            ...first.rows.map((row: any) => ({ ...row, done: true })),
        ];

        const second = await runRule(DEMO_DAILY_RULE_ID, dailyRule.sql, occurrence, withCompleted);
        expect(second.success, second.error).to.equal(true);
        expect(second.rows, "no row is re-inserted or reset").to.deep.equal([]);
    });

    it("returns values the client can store: dates as text, done as boolean", async () => {
        const result = await runRule(DEMO_DAILY_RULE_ID, dailyRule.sql, "2026-03-05T00:00:00Z");
        const schema = parseSchemaString(occurrences.schemaSql);
        const columnTypes = new Map(schema.columns.map((c: any) => [c.name, c.type]));

        // Every schema column is parsed despite the CHECK constraints.
        expect([...columnTypes.keys()]).to.deep.equal([
            "id",
            "task_key",
            "title",
            "cadence",
            "occurrence_date",
            "done",
        ]);

        for (const row of result.rows) {
            expect(typeof row.occurrence_date, "date is returned as text").to.equal("string");
            expect(castValueForColumn(row.done, columnTypes.get("done") as string)).to.equal(false);
            expect(castValueForColumn(row.occurrence_date, columnTypes.get("occurrence_date") as string))
                .to.equal("2026-03-05");
        }
    });

    // A SELECT over a DATE column yields a Date; the rules deliberately render
    // their dates as text instead (see routineOccurrenceSql).
    const asIsoDate = (value: unknown): string => {
        if (typeof value === "string") return value.slice(0, 10);
        // Handle cross-context Date instances in Jest/Mocha
        if (Object.prototype.toString.call(value) === "[object Date]") {
            const d = value as Date;
            return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate())).toISOString().slice(0, 10);
        }
        return String(value).slice(0, 10);
    };

    it("the display query returns only the newest occurrence of each task", async () => {
        // The UI Definition query is a plain SELECT; run it through the same
        // executor to verify the "latest occurrence only" behaviour.
        const result = await runRule(DEMO_DAILY_RULE_ID, occurrences.query, "2026-03-05T00:00:00Z");

        expect(result.success, result.error).to.equal(true);
        const taskKeys = result.rows.map((r: any) => r.task_key);
        expect(new Set(taskKeys).size, "one row per recurring task").to.equal(taskKeys.length);
        expect(taskKeys.sort()).to.deep.equal([
            "daily-inbox",
            "daily-standup",
            "weekly-report",
            "weekly-review",
        ]);
        // Task definitions live in their own table and never show up here.
        expect(result.rows.every((r: any) => !String(r.id).startsWith("routine-template-"))).to.equal(true);

        for (const row of result.rows) {
            const newest = seededRecords
                .filter((r) => r.task_key === row.task_key)
                .map((r) => String(r.occurrence_date))
                .sort()
                .at(-1);
            expect(asIsoDate(row.occurrence_date)).to.equal(newest);
        }
    });
});
