import { expect } from "chai";
import { DateTime } from "luxon";
import * as Y from "yjs";
import {
    buildDemoScheduleRules,
    DEMO_DAILY_RULE_ID,
    DEMO_PROJECT_TITLE,
    DEMO_ROUTINES_TABLE_ID,
    demoTables,
    seedDemoTableDoc,
} from "../../src/demo-content.js";
import { JobScheduler } from "../../src/scheduler/Scheduler.js";

// A full scheduler tick against real Y.Docs: the demo's daily rule is due, so
// the scheduler must find the table's own room, run the SQL and write the
// generated occurrence back into Data Storage.
describe("Job scheduler run", function() {
    this.timeout(30000);

    const projectRoom = `projects/${DEMO_PROJECT_TITLE}`;
    const tableRoom = `${projectRoom}/tables/${DEMO_ROUTINES_TABLE_ID}`;
    const routines = demoTables.find((t) => t.tableId === DEMO_ROUTINES_TABLE_ID)!;
    const dailyRule = buildDemoScheduleRules().find((r) => r.ruleId === DEMO_DAILY_RULE_ID)!;

    let scheduler: JobScheduler;
    let docs: Map<string, Y.Doc>;
    let indexRow: any;
    let updates: { nextRunAt: string; seq: number; }[];
    let openedRooms: string[];
    let seededRecordCount: number;

    beforeEach(() => {
        docs = new Map();

        const projectDoc = new Y.Doc();
        const ruleMap = new Y.Map<unknown>();
        projectDoc.getMap("schedules").set(dailyRule.ruleId, ruleMap);
        ruleMap.set("sql", dailyRule.sql);
        ruleMap.set("catchUp", true);
        docs.set(projectRoom, projectDoc);

        const tableDoc = new Y.Doc();
        seedDemoTableDoc(tableDoc, routines);
        // Drop today's daily occurrences from the seed so the rule has to
        // generate them itself.
        const data = tableDoc.getMap("data");
        for (const id of [...data.keys()]) {
            if (id.endsWith(`-${DateTime.utc().toFormat("yyyy-MM-dd")}`)) data.delete(id);
        }
        seededRecordCount = data.size;
        docs.set(tableRoom, tableDoc);

        // The rule was due yesterday at midnight and has not run yet.
        const due = DateTime.utc().minus({ days: 1 }).startOf("day");
        indexRow = {
            room: projectRoom,
            rule_id: dailyRule.ruleId,
            target_table_id: DEMO_ROUTINES_TABLE_ID,
            timezone: "UTC",
            rrule: dailyRule.rrule,
            dtstart: `${due.toFormat("yyyy-MM-dd")}T00:00:00`,
            next_run_at: due.toISO(),
            occurrence_seq: 0,
            state: "active",
        };

        updates = [];
        openedRooms = [];

        const hocuspocus: any = {
            configuration: { extensions: [] },
            openDirectConnection: async (room: string) => {
                openedRooms.push(room);
                return { document: docs.get(room) ?? null, disconnect: () => {} };
            },
        };

        const sqliteDb = {
            prepare: (sql: string) => ({
                all: () => (/SELECT \* FROM schedule_index/.test(sql) ? [indexRow] : []),
                run: (...args: any[]) => {
                    if (/SET next_run_at/.test(sql)) {
                        updates.push({ nextRunAt: args[0], seq: args[1] });
                        indexRow.next_run_at = args[0];
                        indexRow.occurrence_seq = args[1];
                    } else if (/state = 'completed'/.test(sql)) {
                        indexRow.state = "completed";
                    }
                },
            }),
        };

        scheduler = new JobScheduler(hocuspocus);
        scheduler.setDb(sqliteDb);
        // No immediate tick: every test drives the ticks explicitly.
        scheduler.start(3_600_000, false);
    });

    afterEach(async () => {
        scheduler.stop();
    });

    it("runs a due rule against the table's own room and stores the generated rows", async () => {
        await scheduler.tick();

        expect(openedRooms, "the table subdoc room is used, not the project room").to.contain(tableRoom);

        const data = docs.get(tableRoom)!.getMap("data");
        // catchUp: only the most recent missed occurrence runs, i.e. today's.
        const today = DateTime.utc().toFormat("yyyy-MM-dd");
        const generatedId = `daily-standup-${today}`;
        const record = data.get(generatedId) as Y.Map<unknown> | undefined;

        expect(record, `occurrence ${generatedId} was created`).to.be.instanceOf(Y.Map);
        expect(record!.get("id")).to.equal(generatedId);
        expect(record!.get("kind")).to.equal("occurrence");
        expect(record!.get("task_key")).to.equal("daily-standup");
        expect(record!.get("cadence")).to.equal("daily");
        expect(record!.get("occurrence_date")).to.equal(today);
        expect(record!.get("done"), "a new occurrence starts unchecked").to.equal(false);

        // Weekly tasks are generated by the other rule only.
        expect(data.has(`weekly-review-${today}`)).to.equal(false);
    });

    it("advances the index to the next occurrence and records the run", async () => {
        await scheduler.tick();

        expect(updates.length, "the index cursor moved").to.be.greaterThan(0);
        const last = updates[updates.length - 1];
        expect(DateTime.fromISO(last.nextRunAt, { zone: "utc" }).toMillis())
            .to.be.greaterThan(DateTime.utc().toMillis());
        // The daily rule keeps its scheduled wall clock instead of drifting to
        // the execution time.
        expect(DateTime.fromISO(last.nextRunAt, { zone: "utc" }).toFormat("HH:mm:ss")).to.equal("00:00:00");

        const ruleMap = docs.get(projectRoom)!.getMap("schedules").get(dailyRule.ruleId) as Y.Map<unknown>;
        const lastRunAt = ruleMap.get("lastRunAt");
        expect(typeof lastRunAt, "lastRunAt is an ISO string the UI can parse").to.equal("string");
        expect(Number.isNaN(new Date(String(lastRunAt)).getTime())).to.equal(false);
    });

    it("does not re-create or reset an occurrence that already exists", async () => {
        await scheduler.tick();

        const data = docs.get(tableRoom)!.getMap("data");
        const today = DateTime.utc().toFormat("yyyy-MM-dd");
        const record = data.get(`daily-standup-${today}`) as Y.Map<unknown>;

        // The user completes the task, then the same occurrence is re-run.
        record.set("done", true);
        indexRow.next_run_at = DateTime.utc().minus({ days: 1 }).startOf("day").toISO();
        indexRow.occurrence_seq = 0;
        indexRow.state = "active";
        await scheduler.tick();

        expect(record.get("done"), "the completed checkbox survives a re-run").to.equal(true);
        expect(data.size, "no duplicate occurrence is added").to.equal(seededRecordCount + 2);
    });
});
