import "../utils/registerAfterEachSnapshot";
import { registerCoverageHooks } from "../utils/registerCoverageHooks";
registerCoverageHooks();
/** @feature FTR-6b2f10c7
 *  Title   : Recurring task generation with schedule rules
 *  Source  : docs/client-features/rtk-recurring-task-generation-6b2f10c7.yaml
 */
import { expect, test } from "@playwright/test";

function utcDate(daysFromToday: number): string {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() + daysFromToday);
    return d.toISOString().slice(0, 10);
}

function utcWeekStart(weeksAgo: number): string {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7) - weeksAgo * 7);
    return d.toISOString().slice(0, 10);
}

// The seeded demo tasks (see server/src/demo-content.ts).
const TASK_KEYS = ["daily-inbox", "daily-standup", "weekly-report", "weekly-review"];

// The page embeds two tables: the recurring task definitions and the dated
// occurrences generated from them.
async function openRecurringTasks(page: import("@playwright/test").Page, tableName = "Routine Occurrences") {
    await page.goto("/demo");
    const pageList = page.getByTestId("demo-page-list");
    await expect(pageList).toBeVisible({ timeout: 30000 });
    await pageList.getByText("Recurring Tasks", { exact: true }).first().click();
    await expect(page).toHaveURL(/\/demo\/Recurring%20Tasks$/, { timeout: 15000 });

    const view = page.getByTestId("yjs-table-view").filter({
        has: page.getByTestId("yjs-table-name").getByText(tableName, { exact: true }),
    }).first();
    await expect(view).toBeVisible({ timeout: 30000 });
    // PGlite loads lazily; the first query result can take a while.
    const expectedHeader = tableName === "Routine Templates" ? "cadence" : "template_id";
    await expect(view.getByTestId("yjs-table-grid").locator("th", { hasText: expectedHeader }))
        .toBeVisible({ timeout: 30000 });
    return view;
}

test.describe("FTR-6b2f10c7: recurring tasks generated by schedule rules", () => {
    test.beforeEach(() => {
        test.setTimeout(120000);
    });

    test("shows exactly one row per recurring task: the newest occurrence", async ({ page }) => {
        const view = await openRecurringTasks(page);
        const rows = view.getByTestId("yjs-table-grid").locator("tbody tr");

        await expect(rows).toHaveCount(TASK_KEYS.length, { timeout: 30000 });

        // Each row is the current occurrence of one task: its record id is
        // "<template_id>-<occurrence date>".
        const ids = await rows.evaluateAll((els) => els.map((el) => el.getAttribute("data-record-id") ?? ""));
        expect(ids.slice().sort()).toEqual([
            `daily-inbox-${utcDate(0)}`,
            `daily-standup-${utcDate(0)}`,
            `weekly-report-${utcWeekStart(0)}`,
            `weekly-review-${utcWeekStart(0)}`,
        ]);

        // Every task appears once, identified by its template_id rather than its title.
        const templateIds = await view.getByTestId("yjs-table-grid")
            .locator('td[data-col="template_id"]').allInnerTexts();
        expect(templateIds.map((t) => t.trim()).sort()).toEqual(TASK_KEYS);
    });

    test("hides the earlier occurrences of the same task", async ({ page }) => {
        const view = await openRecurringTasks(page);
        const grid = view.getByTestId("yjs-table-grid");

        // Yesterday's daily occurrence and last week's weekly occurrence are
        // seeded as history but superseded, so they are not displayed.
        for (const supersededId of [`daily-standup-${utcDate(-1)}`, `weekly-review-${utcWeekStart(1)}`]) {
            await expect(grid.locator(`tbody tr[data-record-id="${supersededId}"]`)).toHaveCount(0);
        }

        // Task definitions live in the templates table, not in this one.
        for (const key of TASK_KEYS) {
            await expect(grid.locator(`tbody tr[data-record-id="${key}"]`)).toHaveCount(0);
        }
    });

    test("the definitions are shown in their own templates table", async ({ page }) => {
        const view = await openRecurringTasks(page, "Routine Templates");
        const grid = view.getByTestId("yjs-table-grid");

        // One definition row per recurring task, and no occurrence columns.
        await expect(grid.locator("tbody tr")).toHaveCount(TASK_KEYS.length, { timeout: 30000 });
        const ids = await grid.locator("tbody tr").evaluateAll((els) =>
            els.map((el) => el.getAttribute("data-record-id") ?? "")
        );
        expect(ids.slice().sort()).toEqual(TASK_KEYS.slice().sort());
        await expect(grid.locator("th", { hasText: "occurrence_date" })).toHaveCount(0);
        await expect(grid.locator("th", { hasText: "done" })).toHaveCount(0);
    });

    test("a task can be completed with its checkbox", async ({ page }) => {
        const view = await openRecurringTasks(page);
        const grid = view.getByTestId("yjs-table-grid");
        const row = grid.locator(`tbody tr[data-record-id="daily-standup-${utcDate(0)}"]`);
        await expect(row).toBeVisible({ timeout: 30000 });

        const checkbox = row.locator('td[data-col="done"] input[type="checkbox"]');
        await expect(checkbox).toBeVisible({ timeout: 15000 });
        await expect(checkbox).toBeEnabled();

        // The demo project is shared and anyone may have completed this task
        // already, so the completion state is toggled relative to what it is
        // now instead of assuming it starts unchecked.
        const wasChecked = await checkbox.isChecked();
        await checkbox.setChecked(!wasChecked);

        // The edit goes Yjs -> PGlite -> debounced re-query -> grid, so the
        // new state must survive the round trip.
        const done = grid.locator(
            `tbody tr[data-record-id="daily-standup-${utcDate(0)}"] td[data-col="done"] input`,
        );
        await expect(done).toBeChecked({ checked: !wasChecked, timeout: 15000 });

        // Leave the shared demo as it was found.
        await done.setChecked(wasChecked);
        await expect(done).toBeChecked({ checked: wasChecked, timeout: 15000 });
    });
});
