/**
 * English demo content — the base locale.
 *
 * Every other locale is a sparse override of this pack (see `DemoLocaleContent`
 * in demo-content.ts): a page that has not been translated yet still seeds,
 * in English, rather than disappearing from that locale's demo.
 *
 * Structure lives in demo-content.ts and is shared by every locale; only the
 * strings a visitor reads belong here. This is a function rather than a const
 * because demo-content.ts imports it while it imports demo-content.ts back —
 * a hoisted function declaration is safe in that cycle, a const is not.
 */

import {
    DEMO_ATTACHMENT_IMAGE,
    DEMO_CALENDAR_ID,
    DEMO_GANTT_CALENDAR_ID,
    DEMO_HABITS_TABLE_ID,
    DEMO_HOUR_MAP_CALENDAR_ID,
    DEMO_ROUTINE_OCCURRENCES_TABLE_ID,
    DEMO_ROUTINE_TEMPLATES_TABLE_ID,
    DEMO_SALES_TABLE_ID,
    DEMO_SALES_TARGETS_TABLE_ID,
    DEMO_TASKS_TABLE_ID,
    type DemoLocaleContent,
    demoUtcDate,
} from "./demo-content.js";

export function demoContentEn(): DemoLocaleContent {
    return {
        pages: [
            {
                key: "welcome",
                title: "Welcome",
                lines: [
                    "Welcome to the Outliner Demo!",
                    "This is a public, collaborative demo project. Anyone can edit it, and the content resets every 24 hours.",
                    'You can also reset the content right now with the "Reset demo content" button at the top of the demo project page.',
                    "Each page of this project demonstrates a group of features. Follow the links below to take the tour.",
                    "Feature tour:",
                    "  [Formatting]: bold, italic, strike-through, code, and links.",
                    "  [Outliner Basics]: items, indentation, and keyboard navigation.",
                    "  [Undo and Redo]: one history shared by the outline and the database tables, "
                    + "from the keyboard or the toolbar buttons.",
                    "  [Internal Links]: linking between pages, backlinks, and the graph view.",
                    "  [Search and Commands]: full-text search and the inline command palette.",
                    "  [Selection and Clipboard]: multi-item selection, box selection, copy and paste.",
                    "  [Collaboration]: real-time editing with other users.",
                    "  [Comments and Votes]: discussing and voting on items, with live seeded threads and votes.",
                    "  [Publishing and Sharing]: read-only sharing, scheduled publishing, and snapshots.",
                    "  [Advanced Features]: live database tables with charts, aliases, and attachments.",
                    "  [Tasks and Habits]: task management and habit tracking built on database tables.",
                    "  [Recurring Tasks]: daily and weekly tasks generated by recurring SQL execution.",
                    "  [Calendars]: a query plus a role assignment over its result columns, no data of its own.",
                    "  [Schedule Rules]: automate database operations",
                    "Give it a try! Everything in this project is editable.",
                ],
            },
            {
                key: "formatting",
                title: "Formatting",
                lines: [
                    "This page demonstrates text formatting with Scrapbox-style syntax.",
                    "Click an item to see its raw text with the control characters visible.",
                    "Examples:",
                    "  You can make text [[bold]] using double brackets.",
                    "  You can make text [/ italic] using a slash bracket.",
                    "  You can [-strike through] text using a dash bracket.",
                    "  Inline `code` uses backticks.",
                    "  Formats can be combined, like [[bold with [/ italic]]] inside.",
                    "URLs become clickable links: https://github.com/yjs/yjs",
                    "Try editing any line above to see the syntax behind it.",
                    "  [Internal Links] feature.",
                ],
            },
            {
                key: "outliner basics",
                title: "Outliner Basics",
                lines: [
                    "Every line is an item in an outline tree.",
                    "Keyboard operations:",
                    "  Press Enter to create a new item.",
                    "  Press Tab to indent an item (make it a child of the item above).",
                    "  Press Shift+Tab to unindent an item.",
                    "  Move between items with the arrow keys; the cursor keeps its horizontal position.",
                    "A nested example:",
                    "  Parent item",
                    "    Child item",
                    "      Grandchild item",
                    "    Another child",
                    "Try reorganizing the tree above with Tab and Shift+Tab.",
                ],
            },
            {
                key: "undo and redo",
                title: "Undo and Redo",
                lines: [
                    "Undo and redo run off a single history for the whole project.",
                    "Shortcuts:",
                    "  Ctrl+Z undoes the most recent change.",
                    "  Ctrl+Shift+Z or Ctrl+Y redoes it.",
                    "Toolbar buttons:",
                    "  The Undo and Redo buttons at the top of the window do exactly the same thing as the shortcuts.",
                    "  On a phone they sit in the action toolbar at the bottom — a software keyboard has no Ctrl key, "
                    + "so that is how you reach your history there.",
                    "  Each button is greyed out while there is nothing to undo or redo, and pressing one keeps your "
                    + "cursor and the software keyboard in place.",
                    "The outline and every database table each keep their own change history internally, "
                    + "but you never have to think about which one you are in.",
                    "One stack, in order:",
                    "  Edit a line here, then add a row to a table on the [Advanced Features] page.",
                    "  Press Ctrl+Z twice: the table row goes first, then the edit on this page.",
                    "  Changes made by other people editing the demo at the same time are never undone by you.",
                    "Try it: type something on this line, then undo it.",
                ],
            },
            {
                key: "internal links",
                title: "Internal Links",
                lines: [
                    "Link to another page by writing its name in brackets, like [Formatting].",
                    "Links to pages that do not exist yet look different, and the page is only created once you edit it.",
                    "You can also link to a page in another project with [/project/page] syntax.",
                    "Backlinks: pages that link to the current page are listed in the backlink panel at the bottom.",
                    "The graph view visualizes how the pages of a project are connected.",
                    "More links to explore: [Outliner Basics], [Collaboration]",
                ],
            },
            {
                key: "schedule rules",
                title: "Schedule Rules",
                items: [
                    {
                        text: "Pages can be scheduled to be published at a later time.",
                    },
                    {
                        text:
                            "Tables can run SQL on a recurrence: see [Recurring Tasks] for two live rules that add the tasks of the day and of the week.",
                    },
                    {
                        text:
                            "Open the Schedule tab of a table (for example on the [Tasks and Habits] page) to create a rule of your own.",
                    },
                    {
                        text:
                            "Run now next to Edit and Delete runs a rule's SQL immediately, so you can try it out without waiting for the next occurrence. It leaves the recurrence untouched and works even while the rule is disabled.",
                    },
                ],
            },
            {
                key: "search and commands",
                title: "Search and Commands",
                lines: [
                    "Use the Search button at the top of a page to search across the whole project.",
                    "Recent searches are remembered for quick access.",
                    "The inline command palette opens when you type / inside an item.",
                    'Replace only rewrites item text; page titles stay untouched unless you tick "Include page titles".',
                    "With that option on, renaming a page is confirmed first, and the open page follows its new name.",
                    "Breadcrumbs at the top of each page let you jump back to the project or home.",
                ],
            },
            {
                key: "selection and clipboard",
                title: "Selection and Clipboard",
                lines: [
                    "Select text with the mouse or with Shift+Arrow keys.",
                    "Selections can span multiple items: keep extending past the end of an item.",
                    "Drag in either direction: selecting bottom-to-top highlights exactly the same text as top-to-bottom.",
                    "This line is deliberately long so that it wraps onto more than one line at most window widths; select part of it and the highlight follows each rendered line instead of running past the right edge.",
                    "On a phone or tablet:",
                    "  Tap any character to put the caret there and open the keyboard.",
                    "  Press and hold to select the word under your finger.",
                    "  Keep your finger down and drag to extend the selection, even into the items below.",
                    "  A normal swipe still scrolls the outline as usual.",
                    "Useful shortcuts:",
                    "  Ctrl+L selects the entire line under the cursor.",
                    "  Shift+Alt+Right expands the selection to the end of the line; Shift+Alt+Left shrinks it.",
                    "  Alt+Shift+Arrow keys (or Alt+Shift+mouse drag) create a box selection across items.",
                    "With an active selection you can:",
                    "  Copy and paste it, even when it spans multiple items.",
                    "  Delete the whole selection in one step.",
                    "  Drag and drop the selected text to move it.",
                    "  Apply formatting such as bold or italic to the selected range.",
                    "Try selecting across the items above and copying them.",
                ],
            },
            {
                key: "collaboration",
                title: "Collaboration",
                lines: [
                    "This demo is a shared, real-time collaborative space.",
                    "Open this page in two browser windows and edit it in one of them.",
                    "Changes appear in the other window instantly.",
                    "While others type, you can see their cursors and selections.",
                    "Editing in this demo is anonymous, so feel free to experiment.",
                ],
            },
            {
                key: "comments and votes",
                title: "Comments and Votes",
                items: [
                    { text: "Items can carry comment threads and votes." },
                    {
                        text: "Comments:",
                        children: [
                            { text: "Open an item's comment thread to discuss it with others." },
                            { text: "Items show a badge with the number of comments." },
                        ],
                    },
                    {
                        text: "This item already has a seeded comment thread — open it to read the messages.",
                        comments: [
                            { author: "alice", text: "This is a seeded demo comment." },
                            {
                                author: "bob",
                                text: "Comment threads sync in real time across everyone viewing the demo.",
                            },
                        ],
                    },
                    {
                        text: "Votes:",
                        children: [
                            {
                                text:
                                    "Click the vote count button, or right-click and choose 'Vote for item', to show agreement.",
                            },
                        ],
                    },
                    {
                        text:
                            "This item is already popular (3 votes). Click the vote count button or right-click to add yours.",
                        votes: ["Alice", "Bob", "Carol"],
                    },
                    { text: "Try commenting on or voting for the items above!" },
                ],
            },
            {
                key: "publishing and sharing",
                title: "Publishing and Sharing",
                lines: [
                    "Pages and projects can be shared beyond the people editing them.",
                    "Sharing: generate a read-only token to share a project without giving edit access.",
                    "  Tokens are generated in the Project Settings (gear icon in the top right).",
                    "Scheduled publishing: schedule a page to be published automatically at a later time.",
                    "  The [/demo/Publishing and Sharing/schedule] page lists upcoming publishing tasks and lets you edit or cancel them.",
                    "Snapshots: the snapshot diff viewer shows how a page changed compared to earlier versions.",
                    "  View this page's [/demo/Publishing and Sharing/diff] to see snapshots.",
                ],
            },
            {
                key: "advanced features",
                title: "Advanced Features",
                items: [
                    {
                        text:
                            "A quick tour of the more advanced capabilities. The items below are live components, not just descriptions.",
                    },
                    {
                        text: "Database tables: this item embeds a live table (Yjs data, SQL queries via PGlite). "
                            + "Toggle the Chart view to render the query result as a bar chart.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_SALES_TABLE_ID,
                    },
                    {
                        text:
                            "Clipboard: within one project, copying and pasting a selection that crosses a Grid creates another "
                            + "live view of the same table and Data Storage. Across projects, paste instead creates an independent "
                            + "Grid with a fresh identity, copied schema, UI settings, and a paste-time snapshot of its rows; conflicting SQL "
                            + "names are rewritten, and Calendar blocks retain their portable settings. Press Ctrl/Cmd+Shift+V "
                            + "for Paste Special: choose another live view, an independent copy with or without data, or plain values. "
                            + "Unavailable choices stay visible and explain why. This public demo has only one project, so try "
                            + "the same-project choices here. Cut and paste moves the view "
                            + "without deleting its data. When a cross-project paste has a hidden consequence—such as copying "
                            + "query dependencies, renaming SQL relations, rebinding outline_items, omitting schedule rules, or "
                            + "leaving a cut table in the source—a transient summary names exactly what happened. Outside Outliner "
                            + "the same copy pastes as what you see: a "
                            + "spreadsheet receives the Grid's rows as cells, a document receives them as a table, and "
                            + "with the Chart view open the picture travels with the numbers.",
                    },
                    {
                        text: "Aggregation across tables: this table stores only the monthly targets, "
                            + "but its query joins the Sales table above and compares both series. "
                            + "Every table of a project can be referenced by the name its schema declares.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_SALES_TARGETS_TABLE_ID,
                    },
                    { text: "Aliases: an item can mirror another item and stay in sync with the original." },
                    {
                        text: "Original item: edit me and watch the alias below update.",
                        ref: "alias-source",
                    },
                    {
                        text: "Alias (mirrors the original item above):",
                        aliasTo: "alias-source",
                    },
                    {
                        text:
                            "Attachments: drag and drop images or files onto an item to attach them. This item has a seeded image attachment.",
                        attachments: [DEMO_ATTACHMENT_IMAGE],
                    },
                    { text: "Schedule: the Schedule view shows date-tagged items as a timeline." },
                    { text: "[[2026-07-12]] Date tagged item for the schedule view" },
                ],
            },
            {
                key: "tasks and habits",
                title: "Tasks and Habits",
                items: [
                    {
                        text:
                            "Inline checkboxes can also be used for lightweight, nested task tracking directly in the outline:",
                        children: [
                            { text: "[ ] This is a pending task" },
                            { text: "[x] This is a completed task" },
                        ],
                    },
                    {
                        text:
                            "Practical task management and habit tracking, built as presets of the database table feature. The items below are live tables.",
                    },
                    {
                        text:
                            "Task manager: add tasks with due dates, priorities and repeat intervals. Status and priority options come from the schema's CHECK constraints.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_TASKS_TABLE_ID,
                    },
                    {
                        text:
                            "Habit tracker: one table holds habit definitions and daily completion logs. Add a log row for today to extend a streak.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_HABITS_TABLE_ID,
                    },
                    {
                        text:
                            "Every view is computed with real SQL (Postgres via PGlite) over the collaborative table records, and the schema/query/grid are all editable.",
                    },
                ],
            },
            {
                key: "recurring tasks",
                title: "Recurring Tasks",
                items: [
                    {
                        text:
                            "Daily and weekly tasks, generated by schedule rules: the SQL of a rule runs again at every occurrence of its recurrence and appends the task of that day or week.",
                    },
                    {
                        text: "How it works:",
                        children: [
                            {
                                text:
                                    "Two tables: the templates below define what repeats, the occurrences table collects the dated tasks generated from them.",
                            },
                            {
                                text:
                                    "Two schedule rules write into the occurrences table: one runs every day at 00:00, the other every Monday at 00:00 (UTC).",
                            },
                            {
                                text:
                                    "Each run reads the templates table and inserts one occurrence per definition of its cadence: a rule can query any table of the project, not only the one it writes to.",
                            },
                            {
                                text:
                                    "A recurring task is identified by its task_key, not by its title: renaming a task keeps its history together.",
                            },
                            {
                                text:
                                    "The id of an occurrence is task_key + occurrence date, so re-running the same occurrence changes nothing and never clears a completed checkbox.",
                            },
                            {
                                text:
                                    "The occurrences query shows only the newest occurrence of each task; the earlier ones stay in the table as history.",
                            },
                        ],
                    },
                    {
                        text:
                            "The recurring task definitions. Add a row here and the next run of the matching rule starts generating its occurrences.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_ROUTINE_TEMPLATES_TABLE_ID,
                    },
                    {
                        text:
                            "Tick a checkbox to complete today's (or this week's) task. Tomorrow's run adds a fresh, unchecked occurrence that replaces it in this view.",
                        componentType: "yjstable",
                        yjsTableId: DEMO_ROUTINE_OCCURRENCES_TABLE_ID,
                    },
                    {
                        text:
                            "Open the Schedule tab of the occurrences table to read both rules, edit their SQL or recurrence, or disable them. See also [Schedule Rules].",
                    },
                ],
            },
            {
                key: "calendars",
                title: "Calendars",
                items: [
                    {
                        text:
                            "A calendar is a query plus a role assignment over its result columns — which column is the title, the start, the all-day flag, the duration, and which columns are grouping axes. It has no data of its own.",
                    },
                    {
                        text: "How it works:",
                        children: [
                            {
                                text:
                                    "Candidates are the columns the query actually returns, in result order — never a fixed schema. Changing the query never discards an existing role assignment for a column that is temporarily missing from the new result.",
                            },
                            {
                                text:
                                    'A query must SELECT both "source_kind" and "source_id" for its rows to be writable; otherwise the calendar is read-only and says so.',
                            },
                            {
                                text:
                                    "Reassigning a role, editing the query, or changing group axes are all undoable, on the same shared history as everything else (see [Undo and Redo]).",
                            },
                            {
                                text:
                                    "Drag an entry to reschedule it, drag its bottom edge to resize its duration, or move it with the arrow keys — all three go through the same write path, the same writability check, and the same optimistic-placement model. Switch between Day / Multi-day / Week / Month / Gantt with the toolbar select.",
                            },
                            {
                                text:
                                    'While a drag or resize is in flight, a chip near the pointer shows exactly where the entry will land — "Thu, Aug 3 09:15 – 09:45" for a move, "09:00 – 10:30 (1h30m)" for a resize, a date alone in Month and Gantt — formatted in the calendar\'s own timezone and snapped the same way the drop is, so the label never promises something different from what gets written.',
                            },
                            {
                                text:
                                    "Grouping by \"tags\" splits the week/day view into swimlanes, one per tag, and colour-codes entries in month view. Drag an entry's small handle onto another lane to replace its tag set; hold Ctrl (Cmd on macOS) while dropping to add the lane's tag instead of replacing.",
                            },
                            {
                                text:
                                    "Every outline item a calendar currently shows carries a small calendar icon of its own — the dated items below this block have one. Hover it, or focus it from the keyboard, to read which calendars the item is on and when it is scheduled, formatted in each calendar's own timezone. An item on two calendars lists both, and the icon disappears by itself once no calendar's query matches the item any more.",
                            },
                            {
                                text:
                                    '"New entry" always asks which page to create it under — there is no implicit inbox — and offers previously used destinations first. Deleting an entry always prompts between removing it and just clearing its date, so a keystroke never silently discards writing.',
                            },
                        ],
                    },
                    {
                        text:
                            "A calendar over this project's outline items, already assigned title/start/all-day/duration/due roles and grouped by tags. Try dragging the entries below, or click **Settings** to change the query or reassign a role.",
                        componentType: "calendar",
                        calendarId: DEMO_CALENDAR_ID,
                    },
                    {
                        text: "Scheduled today",
                        start: `${demoUtcDate(0)}T09:00:00.000Z`,
                        allDay: false,
                        duration: "PT30M",
                        tags: ["work"],
                    },
                    {
                        text: "Scheduled tomorrow, longer block",
                        start: `${demoUtcDate(1)}T13:00:00.000Z`,
                        allDay: false,
                        duration: "PT2H",
                        tags: ["urgent"],
                    },
                    {
                        text: "All-day conference",
                        start: demoUtcDate(2),
                        allDay: true,
                        duration: "P2D",
                        tags: ["work", "travel"],
                    },
                    {
                        text: "Deadline only, no start — renders as a marker, not a block",
                        due: `${demoUtcDate(3)}T17:00:00.000Z`,
                    },
                    {
                        text:
                            "Hour Map (#4972): the same day, folded. Each row is one wall-clock hour and the row's own width is that hour's 00-60 minutes, so a long entry wraps across hour rows like a narrow text box — and horizontal length always means real elapsed minutes. Overlapping entries therefore stack into sub-lanes (growing only that hour's row) instead of splitting the width, and the title is drawn once, in the first fragment with room for it.",
                    },
                    {
                        text: "Today by the hour",
                        componentType: "calendar",
                        calendarId: DEMO_HOUR_MAP_CALENDAR_ID,
                    },
                    {
                        text:
                            "Gantt (#4350): one row per entry, nested by this outline's own hierarchy — no separate Gantt hierarchy to define. A parent with dated children shows a rolled-up bar spanning their earliest start to latest end instead of its own dates; dragging it shifts the whole subtree as one undo entry. Axis granularity (day/week/month/quarter) is a view setting.",
                        children: [
                            {
                                text:
                                    "A parent's own due (if any) still renders as a marker alongside its rolled-up bar — the case that makes the roll-up useful: a deadline the children's own schedule may be overrunning.",
                            },
                        ],
                    },
                    {
                        text: "Project plan",
                        componentType: "calendar",
                        calendarId: DEMO_GANTT_CALENDAR_ID,
                    },
                    {
                        text: "Launch plan",
                        due: `${demoUtcDate(20)}T17:00:00.000Z`,
                        children: [
                            {
                                text: "Design",
                                start: demoUtcDate(0),
                                allDay: true,
                                duration: "P3D",
                            },
                            {
                                text: "Build",
                                start: demoUtcDate(3),
                                allDay: true,
                                duration: "P5D",
                                children: [
                                    {
                                        text: "Backend",
                                        start: demoUtcDate(3),
                                        allDay: true,
                                        duration: "P4D",
                                    },
                                    {
                                        text: "Frontend",
                                        start: demoUtcDate(5),
                                        allDay: true,
                                        duration: "P3D",
                                    },
                                ],
                            },
                            {
                                text: "Test",
                                start: demoUtcDate(8),
                                allDay: true,
                                duration: "P2D",
                            },
                        ],
                    },
                ],
            },
        ],
    };
}
