<script lang="ts">
import DiffMatchPatch from "diff-match-patch";
import { onMount } from "svelte";
import {
    addSnapshot,
    getSnapshot,
    listSnapshots,
    replaceWithSnapshot,
    type Snapshot,
} from "../services";

interface Props {
    project: string;
    page: string;
    currentContent: string;
    author: string;
}
let { project, page, currentContent, author }: Props = $props();

let snapshots = $state<Snapshot[]>([]);
let selectedId = $state("");
let diffHtml = $state("");
const dmp = new DiffMatchPatch();

function refresh() {
    snapshots = listSnapshots(project, page);
}

function showDiff(id: string) {
    selectedId = id;
    const snapshot = getSnapshot(project, page, id);
    if (!snapshot) return;
    const diff = dmp.diff_main(snapshot.content, currentContent);
    dmp.diff_cleanupSemantic(diff);
    diffHtml = dmp.diff_prettyHtml(diff);
}

function revert() {
    if (!selectedId) return;
    const snap = replaceWithSnapshot(project, page, selectedId);
    if (snap) {
        currentContent = snap.content;
        refresh();
        showDiff(selectedId);
    }
}

onMount(() => {
    refresh();
});

$effect(() => {
    if (project && page) refresh();
});
</script>

<div class="bg-white rounded shadow-lg p-4">
    <h2 class="text-lg font-bold mb-2" id="diff-modal-title">History / Diff</h2>

    <div class="flex gap-4 h-96">
        <div class="w-1/3 border-r overflow-hidden flex flex-col">
            <h3 class="visually-hidden" id="snapshot-list-label">Snapshots</h3>
            <ul
                class="overflow-y-auto flex-1 pr-2 space-y-1"
                aria-labelledby="snapshot-list-label"
            >
                {#if snapshots.length === 0}
                    <li class="text-gray-500 italic p-2" role="status">No snapshots available</li>
                {/if}

                {#each snapshots as s (s.id)}
                    {@const isSelected = selectedId === s.id}
                    <li>
                        <button
                            type="button"
                            aria-pressed={isSelected}
                            class="w-full text-left p-2 rounded text-sm transition-colors duration-200 {isSelected ? 'bg-blue-50 text-blue-700 border-l-4 border-blue-600' : 'hover:bg-gray-100'}"
                            onclick={() => showDiff(s.id)}
                        >
                            <span class="block font-medium">
                                {new Date(s.timestamp).toLocaleString()}
                            </span>
                            <span class="block text-xs text-gray-500">
                                {s.author}
                            </span>
                        </button>
                    </li>
                {/each}
            </ul>
        </div>

        <div class="flex-1 flex flex-col overflow-hidden">
            <h3 class="visually-hidden">Diff View</h3>
            <!-- Added .diff class for backward compatibility with existing tests -->
            <div
                class="diff diff-view flex-1 overflow-auto bg-gray-50 p-3 rounded border border-gray-200 font-mono text-sm"
                tabindex="0"
                role="region"
                aria-label="Diff content"
            >
                {#if diffHtml}
                    <!-- XSS-safe: diffHtml is generated by trusted diff-match-patch library -->
                    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
                    {@html diffHtml}
                {:else}
                    <div class="flex items-center justify-center h-full text-gray-400 italic">
                        Select a snapshot to view differences
                    </div>
                {/if}
            </div>
        </div>
    </div>

    <div class="mt-4 flex justify-end space-x-2">
        <button
            class="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition-colors text-sm font-medium"
            onclick={() => {
                addSnapshot(project, page, currentContent, author);
                refresh();
            }}
        >
            Add Snapshot
        </button>
        <button
            class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            onclick={revert}
            disabled={!selectedId}
            aria-disabled={!selectedId}
            title={!selectedId ? "Select a snapshot first" : "Revert to selected snapshot"}
        >
            Revert
        </button>
    </div>
</div>

<style>
/* Using utility class pattern for visually hidden content */
.visually-hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
}

/* Diff styles */
:global(.diff-view ins) {
    background-color: #dcfce7;
    color: #166534;
    text-decoration: none;
    padding: 0 0.125rem;
    border-radius: 0.125rem;
}

:global(.diff-view del) {
    background-color: #fee2e2;
    color: #991b1b;
    text-decoration: line-through;
    opacity: 0.8;
    padding: 0 0.125rem;
    border-radius: 0.125rem;
}
</style>
