name: 'Setup Test Environment'
description: 'Sets up the environment for testing (install dependencies, restore cache, clean ports)'

runs:
  using: "composite"
  steps:
    - name: Install Java 21
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jre-headless

    - name: Restore dependencies from cache
      shell: bash
      run: |
        # Copy pre-installed node_modules from cache
        if [ -d "/cache/client/node_modules" ]; then
          cp -r /cache/client/node_modules client/
        fi
        if [ -d "/cache/server/node_modules" ]; then
          cp -r /cache/server/node_modules server/
        fi
        if [ -d "/cache/functions/node_modules" ]; then
          cp -r /cache/functions/node_modules functions/
        fi
        
        # Ensure binaries are executable
        chmod +x client/node_modules/.bin/* || true
        chmod +x server/node_modules/.bin/* || true
        chmod +x functions/node_modules/.bin/* || true

    - name: Install scripts dependencies
      shell: bash
      run: |
        cd scripts
        npm ci

    - name: Install pm2
      shell: bash
      run: |
        npm install -g pm2

    - name: Setup test environment
      shell: bash
      run: |
        # Clean up any existing processes on test ports
        echo "Cleaning up existing processes..."
        cd "$(pwd)"
        if [ -f "scripts/kill-tinylicious.js" ]; then
          node scripts/kill-tinylicious.js || echo "Process cleanup script failed, continuing..."
        fi

        # Manual cleanup as fallback
        pkill -f "port 7090" || true
        pkill -f "tinylicious" || true
        pkill -f "firebase" || true
        pkill -f "vite" || true

        # Wait for ports to be freed
        sleep 5

    - name: Run setup script
      shell: bash
      env:
        CI: true
        NODE_ENV: test
        TEST_ENV: localhost
        DISPLAY: :99
        DISABLE_POSTHOG: true
        VITE_DISABLE_FLUID_TELEMETRY: true
        PREINSTALLED_ENV: true
        SKIP_SERVER_START: "0"
        SKIP_PORT_WAIT: "0"
      run: |
        # Create sentinel file to skip dependency installation in setup.sh
        touch .setup-installed
        
        # Retry setup.sh up to 3 times
        MAX_RETRIES=3
        RETRY_DELAY=10
        count=0
        success=false
        
        while [ $count -lt $MAX_RETRIES ]; do
          if bash scripts/setup.sh; then
            success=true
            break
          else
            count=$((count + 1))
            if [ $count -lt $MAX_RETRIES ]; then
              echo "Setup failed. Retrying in $RETRY_DELAY seconds... (Attempt $count/$MAX_RETRIES)"
              sleep $RETRY_DELAY
            else
              echo "Setup failed after $MAX_RETRIES attempts."
            fi
          fi
        done
        
        if [ "$success" = "false" ]; then
          exit 1
        fi
