name: 'Setup Test Environment'
description: 'Sets up the environment for testing (install dependencies, restore cache, clean ports)'

runs:
  using: "composite"
  steps:
    - name: Install Java 21
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jre-headless

    - name: Restore dependencies from cache
      shell: bash
      run: |
        # Copy pre-installed node_modules from cache
        if [ -d "/cache/client/node_modules" ]; then
          cp -r /cache/client/node_modules client/
        fi
        if [ -d "/cache/server/node_modules" ]; then
          cp -r /cache/server/node_modules server/
        fi
        if [ -d "/cache/functions/node_modules" ]; then
          cp -r /cache/functions/node_modules functions/
        fi
        
        # Ensure binaries are executable
        chmod +x client/node_modules/.bin/* || true
        chmod +x server/node_modules/.bin/* || true
        chmod +x functions/node_modules/.bin/* || true

    - name: Setup test environment
      shell: bash
      run: |
        # Clean up any existing processes on test ports
        echo "Cleaning up existing processes..."
        cd "$(pwd)"
        if [ -f "scripts/kill-tinylicious.js" ]; then
          node scripts/kill-tinylicious.js || echo "Process cleanup script failed, continuing..."
        fi

        # Manual cleanup as fallback
        pkill -f "port 7090" || true
        pkill -f "tinylicious" || true
        pkill -f "firebase" || true
        pkill -f "vite" || true

        # Wait for ports to be freed
        sleep 5

    - name: Run codex setup script
      shell: bash
      env:
        CI: true
        NODE_ENV: test
        TEST_ENV: localhost
        DISPLAY: :99
        DISABLE_POSTHOG: true
        VITE_DISABLE_FLUID_TELEMETRY: true
        PREINSTALLED_ENV: true
      run: |
        # Create sentinel file to skip dependency installation in setup.sh
        touch .setup-installed
        bash scripts/setup.sh
